env:
  browser: true
  es2021: true
extends:
  - react-app
  - react-app/jest
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:testing-library/react
  - prettier # this needs to stay last to be able to override other configs
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - import
rules:
  react/react-in-jsx-scope: off
  semi:
    - error
    - never
  '@typescript-eslint/explicit-member-accessibility':
    - warn
    - accessibility: no-public
  '@typescript-eslint/no-empty-function':
    - error
    - allow:
        - constructors
  '@typescript-eslint/no-redeclare': off
  'import/no-default-export': error
  'react/prop-types': off
  'testing-library/no-debugging-utils':
    - warn
    - utilsToCheckFor:
        debug: false
root: true
