name: Test

on:
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
  # Allow manual run if necessary
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['22']
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Enable pnpm
        run: |
          corepack enable pnpm
          pnpm -v
      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v5
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Audit
        run: pnpm audit
      - name: Build Backend
        run: pnpm run build:backend
      - name: Build App
        run: pnpm run build:app
